version: "3.8"
services:
  db:
    image: "mongo:latest"
    container_name: qurb_db
    networks:
      shared-net:
        ipv4_address: 192.168.0.2
    expose:
      - 27017
  backend:
    build: "./server"
    image: "deerarif/qurb_serv:1.0"
    container_name: qurb_serv
    expose:
      - 5000
    networks:
      shared-net:
        ipv4_address: 192.168.0.3
    depends_on:
      - db
  react:
    build: "./client"
    image: deerarif/qurb_react
    container_name: qurb_react
    ports:
      - "80:3000"
    networks:
      shared-net:
        ipv4_address: 192.168.0.4
    depends_on:
      - backend
  wa:
    build: "./whatsapp"
    image: deerarif/wabot:1.0
    container_name: qurb_wa
    expose:
      - 8000
    networks:
      shared-net:
        ipv4_address: 192.168.0.5
networks:
  shared-net:
    ipam:
      config:
        - subnet: 192.168.0.1/24
